In [8]:
import numpy as np
c=np.arange(5)
print(c)
c.shape

[0 1 2 3 4]


(5,)

In [19]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_2=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(arr)
arr.ndim # ndim -> show the dimension of the array
arr_2.ndim
#arr.shape # show how many rows and columns in array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


3

In [3]:
import numpy as np
arr_3=np.array([1,2,3,4,5],ndmin=3) # in higher order array we can pass ndmin arugment
print(arr_3)
idx=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(f"indices: {idx[0,0]}") # [rows ,columns] represent
idx.shape

[[[1 2 3 4 5]]]
indices: 1


(2, 5)

In [6]:
import numpy as np
a=np.array([6,4,2,1,7,8,2])
np.sort(a)
print(a[2:5]) # slice the array function
print(a.size) # show the array size


[2 1 7]
7


In [17]:
import numpy as np
a=np.array([1,2,3,4,5])
a.shape
a2=a[np.newaxis,:] # add new axis
a2.shape
b=np.expand_dims(a,axis=1)

(5, 1, 1)