Here try some methods of numpy

In [11]:
import numpy as np
arr=np.array([1,2,3,4])
z=sum(arr)
print(z)
print(arr.dtype) # show the data type of the array
newarr=arr.astype('i') 
print(newarr.dtype)

10
int32
int32


In [6]:
import numpy as np
arr2=np.array([11,23,24,25,7])
x=arr2.copy()
arr2[0]=100 # replace the first of the array by 100
print(arr2)
y=np.where(arr2==24) # search element in array
print(y)
z=np.sort(arr2) # putting elements in sequances 
print(z)

[100  23  24  25   7]
(array([2], dtype=int64),)
[  7  23  24  25 100]


In [16]:
# iterating method
import numpy as np
#for x in arr2: # here arr2 is use the above code
    #print(x)

# for 2-D is :
two_D=np.array([[1,2,3,4],[5,6,7,8]])
for x in two_D:
    for y in x:
        print(y)

1
2
3
4
5
6
7
8
