In [15]:
import numpy as np
np.arange(3)
# creation of the Array
arr=np.array([1,2,3,4,5])
print(arr)
arr.shape

# 2D Array creation
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
arr2.shape
arr2.ndim

#3D Array creation 
arr3=np.array([[[9,10,11,12],[13,14,15,16],[17,18,19,20]]])
print(arr3)
arr3.ndim

[1 2 3 4 5]
[[1 2 3 4]
 [5 6 7 8]]
[[[ 9 10 11 12]
  [13 14 15 16]
  [17 18 19 20]]]


3

In [27]:
# how to access the element by index
import numpy as np
idx=np.array([1,2,3,4,5])
print(idx[0])
print(idx[1]+idx[2]) # addition through indics

# 2D elements access through indices
two_D=np.array([[1,2,3,4],[5,6,7,8]])
print("access the 2D elements ",two_D[[0,1],[1,2]])

#3D elements access through indices 
three_D=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D elements is : ",three_D[0,1,2])


1
5
access the 2D elements  [2 7]
3D elements is :  6


In [36]:
# Here some methods to try
import numpy as np
slic=np.array([1,2,3,4,5])
print(slic[1:3])
print(slic[2:]) # after 2 all elements are show 
print(slic[:2]) # before 2 all elements are show 

[2 3]
[3 4 5]
[1 2]
