In [15]:
# generate integer number 
from numpy import random
x=random.randint(100 ,size=5) # generate a random numbers with in range of 100
print(x)   # randint take size parameter which make a array

[49 20 71 29 59]


In [21]:
from numpy import random
x=random.rand(5) # rand() generate a float values 
z=random.randint(50, size=5) # generate the Array
y=random.choice(z)
print("random retrun value from the array:",y)
print(x)

random retrun value from the array: 28
[0.80130111 0.34329632 0.19355762 0.11142455 0.45548911]


Data Distribution : A list of all possible values and how often each value occurs.
=> the sum of all probability number should be 1.


In [9]:
from numpy import random
data_dis=random.choice([5,6,7,4], p=[0.1,0.5,0.0,0.4],size=(10)) # check probabilty of number that how many chances of number they print 
print(data_dis)


# generate 2_D array from array and select the probability
two_D=random.choice([5,6,7,4], p=[0.1,0.5,0.0,0.4],size=(2,3)) 
print(two_D)

[6 4 6 4 6 5 6 4 6 6]
[[6 6 5]
 [6 4 4]]
